### PR TITLE
Fix bugs

### PR DESCRIPTION
**Pull request by XanatosX**
Add file logging
Add file deletion
Add file deletion map
Add folder creation if required

This pull request will fix the problems with the current patch implementation

### CODE REVIEW

**Comment by Ausgeben** [comment]
Add Marks like [mark] (mark) or smt to mark what this is (info, warning, etc maybe to add)

**Comment by Ausgeben** [comment]
Make a Debug mode, write these lines maybe also in a different window when a value is on debug mode

**Comment by XanatosX** [comment]
> 
> 
> Make a Debug mode, write these lines maybe also in a different window when a value is on debug mode

Well this is an extra cmd window which is showed while the files are getting replaced. Since it required 5 inputs from the calling application I don't think we can make a debug mode for this one.

It will write a log file to temp folder so we can detect future errors.

**Comment by XanatosX** [comment]
> 
> 
> Add Marks like [mark] (mark) or smt to mark what this is (info, warning, etc maybe to add)

Not sure if I do understand this one, do you mean in the headline of the pr?

**Review by Ausgeben — APPROVED** [review]

**Pull request merged**
